name: 'Run golangci-lint with reviewdog'
description: '🐶 Run golangci-lint with reviewdog on pull requests to improve code review experience.'
author: 'Yoshikawa Taiki'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    required: true
  golangci_lint_flags:
    description: 'golangci-lint flags. (golangci-lint run --out-format=line-number <golangci_lint_flags>)'
    default: ''
  tool_name:
    description: 'Tool name to use for reviewdog reporter'
    default: 'golangci'
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review,github-check].'
    default: 'github-pr-review'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'check-circle'
  color: 'blue'